# Generated by Django 2.1.1 on 2019-09-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isehan', '0003_auto_20190918_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description1',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='isehan.ParentCategory', verbose_name='親カテゴリー'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_category', to='isehan.ParentCategory', verbose_name='親カテゴリー'),
        ),
    ]
