# Generated by Django 2.1.1 on 2019-12-31 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isehan', '0004_auto_20190918_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='isehan.ParentCategory', verbose_name='親カテゴリー'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_category', to='isehan.ParentCategory', verbose_name='親カテゴリー'),
        ),
    ]
