# Generated by Django 2.1.1 on 2019-12-31 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isehan', '0005_auto_20191231_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='isehan.ParentCategory', verbose_name='親カテゴリー'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='名前'),
        ),
    ]
