# Generated by Django 2.2.9 on 2020-02-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isehan', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category4',
        ),
    ]
